### ISSUE TITLE
Tag your releases

### ISSUE THREAD

**Issue by dtolnay** [servo/bincode#132]
There are a lot of releases missing from here: https://github.com/TyOverby/bincode/releases

Tags are helpful for being able to navigate to code of old releases and share links to them. For example the first link is a lot more readable and friendly than the second link.

- https://github.com/TyOverby/bincode/blob/v0.5.8/src/lib.rs#L45
- https://github.com/TyOverby/bincode/blob/1fdd49edeefd0d71bdbf27f06392885748d1374f/src/lib.rs#L45

**Comment by dtolnay** [comment]
Also releases are nice because the release notes are emailed out to us watchers.

**Comment by TyOverby** [comment]
Hmm.  I have been tagging the recent alpha releases, but the release notes for 1.0 have been just building up in /changelist.org

**Comment by dtolnay** [comment]
Most importantly, 0.8.0 is not tagged.

**Comment by ZoeyR** [comment]
Closing this since releases back to v0.4.1 have been tagged.
