### ISSUE TITLE
Provide opt-in variable length integer encoding

### ISSUE THREAD

**Issue by dtolnay** [servo/bincode#182]
Maybe something like:

```rust
#[derive(Serialize, Deserialize)]
struct Example {
    #[serde(with = "bincode::varint")]
    a: usize,
    #[serde(with = "bincode::varint")]
    b: i32,
}
```

**Comment by fst3a** [comment]
Perhaps this should affect all occurrences of types that can be encoded with variable length and this should be configurable in Config trait?  As of now there appears to be no nice way in serde to add hints to fields so per-field/per-struct opt-ins would end up being implementation-specific.

I also believe that having variable ints always enabled would harm entropy-coding compressablity of the data by compression algorithms like LZO so being able to disable varints would be nice.

**Comment by whimboo** [comment]
To implement eg. the ADB protocol an encoded length of 4 bytes is used. @dtolnay, would that be possible to define via this issue request, or is it something else?

**Comment by Tolsi** [comment]
[PTAL](https://github.com/sirkibsirkib/serde_varint)
