### ISSUE TITLE
deserialize Cow should be decoding into slices

### ISSUE THREAD

**Issue by RReverser** [servo/bincode#224]
Currently if I encode, for example, `Cow<String>`, and deserialize it back using `deserialize` (that is, passing a complete slice of bytes and not just a stream), I get a `Cow::Owned` back even though I own the entire buffer, and so could have a cheap allocation-free decoding into `Cow::Borrowed`.

Note that when decoding into explicit `&str`, this produces a reference as expected.

**Comment by dtolnay** [comment]
`#[serde(borrow)]` gives you a borrowed `Cow<str>`. https://serde.rs/borrow.html

**Comment by RReverser** [comment]
Oh nice. Why isn't it a default for non-owned deserialization though?

**Comment by dtolnay** [comment]
The deserialize impl is:

```rust
impl<'de, 'a, T: ?Sized> Deserialize<'de> for Cow<'a, T>
```

The borrow attribute effectively gives you:

```rust
impl<'de, T: ?Sized> Deserialize<'de> for Cow<'de, T>
```

In my experience the first one is usually what people want for the ways that Cow is commonly used. For example it lets you serialize and deserialize a struct containing Cow where the data is always borrowed on the way out and owned on the way in without needing to hold on to the serialized data.

The second one is relatively uncommonly used.

**Comment by RReverser** [comment]
It's just a bit surprising that we have two deserialization entry points, one that assumes holding onto the entire input (and so can decode &str, &[u8] etc.) and another that can't assume that as it operates on streams and so can produce only owned values. Yet both entry points produce owned values for Cow by default, even though its contents are subject to exactly same assumptions about having the actual data blob stored elsewhere.

Wouldn't it be possible / make sense to specialize Cow to parse references by default when entire data is available and only owned values otherwise, just like it does for "regular" data types?

If my struct consists of various fields some of which are pure references and some are Cows, it's already bound to the input data because of the former, and so could as well deserialize references in the latter case.

**Comment by ZoeyR** [comment]
This issue would need to be raised with the serde repo itself since it controls how Cow is deserialized.
