### ISSUE TITLE
Add impl From<bincode::Error> for std::io::Error

### ISSUE THREAD

**Issue by imp** [servo/bincode#227]
There is a reverse conversion, but this one is missing. It will help quite a lot when used with `?` operator.

**Comment by glehmann** [comment]
that would also make `bincode::Error` compatible with custom_error.
If there is no opposition to adding this feature, I may give it a try and propose a pull request.

See https://github.com/lovasoa/custom_error/issues/21

**Comment by ZoeyR** [comment]
implementing `From<bincode::Error>` for `std::io::Error` would be a lossy conversion. There are many error cases that would just get thrown away and `From` really isn't meant for lossy conversions
