### ISSUE TITLE
Serializing strings as C-Style strings (null-terminated)

### ISSUE THREAD

**Issue by Waelwindows** [servo/bincode#238]
Can you serialize the string `"Test"` as `"Test\00"` using bincode?

It doesn't matter which string type it is, but it's preferable to not implement a new string type in rust

**Comment by ZoeyR** [comment]
I don't think this makes sense for bincode. Rust strings are not null terminated and can even contain null bytes. I could see this making sense for cross-language compat if Rust strings couldn't have null bytes, but since they can other languages would need to do processing anyways.

**Comment by SArpnt** [comment]
rust has a CString type that requires null termination and has no null in the middle, so it's in some sense a rust type and afaik doesn't need much processing.

i haven't looked at the codebase or api much (i found this project while trying to implement the same thing myself) but i believe the code would look something like this
```rs
let mut buf = Vec::<u8>::default();
reader.read_until(0, &mut buf)?;
if let Some(0) = buf.last() {
	// safe because it's impossible for nul to be in the middle of the buffer
	Ok(unsafe { CString::from_vec_with_nul_unchecked(buf) })
} else {
	Err(/* eof before null terminator error */)
}
```
this might be useful for less processing when cstrings are being used in code or to save space in large files with many strings.
