### ISSUE TITLE
Document forwards and backwards compatibility. 

### ISSUE THREAD

**Issue by kevincox** [servo/bincode#244]
It would be very useful to document compatibility between binaries using bincode. For example which cahnges are safe to make to a structure or enum and still have compatibility? Also things like should I be worried about sending data between OSes, endinesses or rustc versions. 

Thanks.

**Comment by camerondavison** [comment]
this is the first thing i was looking for

**Comment by thedodd** [comment]
This would definitely be good to know.

**Comment by thedodd** [comment]
This seems to be based purely on serde's forward/backward compatibility standards.

**Comment by ZoeyR** [comment]
tracking in #221

**Comment by kevincox** [comment]
It's not clear to me that #221 actually addresses this specifically. I'm not worried about other implementations or other languages. This is specificly asking about the same software using this bincode crate but possibly on different platforms or using slightly different versions. 

Let me know if you would prefer to keep these two separate or if I should highlight these concerns in the other issue.

**Comment by ZoeyR** [comment]
Concerns should be raised in the other issue. By creating a specification we are holding ourselves to a certain standard of bytestream stability. The specification would also cover what changes to structs are, and are not, backwards compatible.
