### ISSUE TITLE
example for a custom serialization and deserialization

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [servo/bincode#270]
Where could I find an example on how to build a custom serializer / deserializer with bincode for my structure? Or do I have to implement my own functions to replace `bincode::serialize` and `bincode::deserialize`?

**Comment by jdm** [comment]
@Hugo-Trentesaux I'm not sure I understand what you are asking. Could you give a code example of what you are trying to accomplish?

**Comment by Hugo-Trentesaux** [comment]
For example, I have an `enum` that I know can only take two values (a hash or a signature). I would like to store the variant on only 1 byte instead of 8. For now, I'm using two `option`, but that's does not represent what I want (I never have both hash and signature).

**Comment by jdm** [comment]
I don't believe there is anything specific to bincode involved in that. You would write a custom Serialize/Deserialize implementation for your type, and if you ran bincode::serialize on it then it would be invoked appropriately.

**Comment by jdm** [comment]
https://github.com/servo/ipc-channel/blob/master/src/ipc.rs#L802-L822 is not a super clear example, but it does show a custom serialization that is used with the bincode serializer.
