### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by carllin** [servo/bincode#280]
Wondering when the next release will be, thanks!

**Comment by jdm** [comment]
@nox Could you add the cargo-publish github group as a crate owner? 1.1.5 is ready to be published but I don't have permission.

**Comment by nox** [comment]
@jdm I added `cargo-publish`, but the thing that landed after 1.1.4 is a new feature, so please release 1.2.0 instead.

**Comment by jdm** [comment]
Done!
