### ISSUE TITLE
Support non-64bit lengths.

### ISSUE THREAD

**Issue by tkaitchuck** [servo/bincode#285]
In the documentation is says:
```
str is encoded as (u64, &[u8]), where the u64 is the number of bytes contained in the encoded string.
```

I am looking for a way around this to explicitly control how the length is serialized. This is similar to: https://github.com/servo/bincode/issues/182
and 
https://github.com/servo/bincode/issues/238

I could not find a good way to implement this even manually. I can create a custom type and implement Serialize, but calling `serialize_bytes()` adds a length prefix and there doesn't appear to be any other way to induce a call to `write_all()`.

Would it be possible to do this by adding a Bincode specific trait extending Serialize perhaps? 
If that can be solved Deserialization seems like it should be straight forward.

**Comment by Tolsi** [comment]
I really like this project for data serialization in Rust but the type of size storage - this is the most significant drawback of it and it is unfortunate that such PRs and issues are ignored.

**Comment by jdm** [comment]
Which PRs are ignored? bincode is a project that currently serves the needs of the project maintainers, so most changes are driven by consumers that are willing to make the necessary changes.

**Comment by tkaitchuck** [comment]
@jdm What are your thoughts on mu suggestion above? Should I send a PR?

**Comment by Tolsi** [comment]
@tkaitchuck you can finish the work on it in #271

**Comment by tkaitchuck** [comment]
As far as I can tell the most general solution for serialization would be to add the method 
```
fn custom_serialize<T: ?Sized + CustomSerialize>(&self, t: &T) -> Result<Vec<u8>>
```
Where the trait `CustomSerialize` has one method:
```
fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error> where S: bincode::CustomSerializer
```
Where `CustomSerializer: serde::Serializer` with the additional method:
```
fn serialize_raw(self, v: &[u8]) -> Result<Self::Ok, Self::Error>
```
Which serialializes bytes as written with no header. 

There can be a blanket implementation for serde::Serialize for things implementing CustomSerialize.
Then the 

Then on the deserialization side: one just needs to implement `Deserialize` for the type requiring custom serialization.

**Comment by tkaitchuck** [comment]
The only major downside I see is that it requires custom serializers for the basic type and any wrapping type that are bincode aware. 
Ideally we could do this in a way that works similar to [serde_bytes](https://docs.serde.rs/serde_bytes/index.html) where the field is annotated. However I am not sure how to implement that without having one of: Specialization, help from serde, or having a parallel mirror of serde's visitor logic.

**Comment by tkaitchuck** [comment]
Perhaps it would be preferable to set these as part of the config.
It would limit the number of options to a fixed set, and would not permit mixed lengths for different objects of the same type. But it would be much easier to use.

**Comment by tkaitchuck** [comment]
This could be done by adding two new options to the config like:
```
#[derive(Clone, Copy)]
enum StringLengthOption {
    VarInt,
    U64,
    U32,
    U16,
    U8,
}
```
and 
```
#[derive(Clone, Copy)]
enum ArrayLengthOption {
    VarInt,
    U64,
    U32,
    U16,
    U8,
}
```

**Comment by Rua** [comment]
The implementation I had in mind was to annotate it on the type itself somehow. Something like
```
#[derive(Deserialize)]
struct Foo {
     [bincode_length(u8)]
     member: Vec<i16>,
}
```
I have no idea if that's possible, but that method would work very well for me.

**Comment by maciejhirsz** [comment]
@Rua attributes can only be added in the `serde::Deserialize` proc macro, so that would be outside of the scope of this crate.

@tkaitchuck I believe if we want this to not affect performance, it should use 0-sized structs with trait implementations that switch between varint, u64, etc., kind of [how `SizeLimit` is done for `Infinite`](https://github.com/servo/bincode/blob/12f1415b9ec5d2eec7712784da7690571b56a7d6/src/internal.rs#L162-L191), otherwise you will introduce extra branching logic for every length. Same should be done for enum variant sizes.

**Comment by vi** [comment]
Shall `bincode2` be merged into `bincode` for this?

**Comment by ZoeyR** [comment]
Closing in favor of #319
