### ISSUE TITLE
Please restore tests in published crate

### ISSUE THREAD

**Issue by kentfredric** [servo/bincode#290]
https://github.com/servo/bincode/commit/80722cc106ef4b34342a2e5a6f88a2c31f1d6890 

https://github.com/servo/bincode/blob/12f1415b9ec5d2eec7712784da7690571b56a7d6/Cargo.toml#L4-L6

This strips tests from the published crate, but all the `dev-dependencies` are still listed.

This means consumers (eg: Linux Vendors such as debian, gentoo, fedora) are unable to run any useful tests for Quality Assurance purposes, but the Cargo configuration will still require dependencies to be fetched, and built, in order to run no tests.

The tests themselves don't seem problematic or bloaty, so I don't see any *good* reason to be avoiding a mere 15k.

If publishing with the whole test suite is undesirable, perhaps split the test suite into 2, and then only strip some of it, not all of it?

**Comment by jdm** [comment]
The 15k argument seems reasonable to me. In the absence of other contrary views, I'd be willing to merge a pull request that restored the tests.
