### ISSUE TITLE
Is serialization size of T guaranteed to be <= size_of::<T>()?

### ISSUE THREAD

**Issue by EkardNT** [servo/bincode#291]
The readme file says that "The size of the encoded object will be the same or smaller than the size that the object takes up in memory in a running Rust program." I can't find similar claims in the actual API documentation though. Does bincode actually guarantee that serialized size will be no more than in-memory size, or is it a case of "usually it will, but there might be edge cases where serialized size may be larger"?

Specifically, when serializing a struct `T`, if I allocate a `vec[0u8, size_of::<T>()]`, am I guaranteed to have enough space for all possible instances of T?

The reason I ask is that I need to serialize an enum and my serialization logic will be much simpler if I can preallocate once and know that I'll never need to resize due to needing more space.

**Comment by dtolnay** [comment]
The readme is not accurate, there is no relationship in general between size in memory and size of a serialized representation.

```rust
use serde::ser::{Serialize, SerializeSeq, Serializer};

struct Struct;

impl Serialize for Struct {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut seq = serializer.serialize_seq(Some(100))?;
        for i in 0..100u32 {
            seq.serialize_element(&i)?;
        }
        seq.end()
    }
}

fn main() {
    println! {
        "{} {}",
        std::mem::size_of::<Struct>(),
        bincode::serialize(&Struct).unwrap().len()
    }
}
```

**Comment by EkardNT** [comment]
Good point about the possibility of arbitrary amplification possibilities, I hadn't considered that. Question answered, thanks.
