### ISSUE TITLE
Is it possible to instantiate a Serializer manually so I can use serde-transcode?

### ISSUE THREAD

**Issue by rw** [servo/bincode#300]
Related to #242, I want to use bincode with serde-transcode. However, it seems that it is not the intended behavior of bincode to let me create a Serializer manually.

I *think* that if I could instantiate `Options` myself, that would solve my problem. One way to do that would be to make `DefaultOptions` accessible to users of this crate. Currently, it is private. 
https://github.com/servo/bincode/blob/master/src/config.rs#L13

Is there interest in doing this?

Thanks!

cc @jean-airoldie

**Comment by jdm** [comment]
I would take a pull request that exposes DefaultOptions.

**Comment by djugei** [comment]
this would also be useful to serialize streaming data. i will probably send a pr tomorrow since it seems like a small change.

**Comment by ZoeyR** [comment]
Would using the `SerializerAcceptor` allow you to use with `bincode` with `serde-transcode`?  This is not a part of the stable public API yet but you should be able to test it out.
