### ISSUE TITLE
Usage with erased_serde

### ISSUE THREAD

**Issue by aclysma** [servo/bincode#301]
I'm trying to use erased_serde with bincode. I have a type registry that generates closures for each type to allow for serializing/deserializing the data. (https://github.com/kabergstrom/prefab/blob/f9b9a9a63be16ac08b6ffe7b9ba97bca6184e76f/legion-prefab/src/registration.rs)

It looks like the only way to get a bincode serializer is to implement bincode::SerializerAcceptor. My implementation needs to erase the serializer and provide it to the type registry. Something like this:

```rust
    fn accept<T: serde::Serializer>(
        self,
        ser: T,
    ) -> Self::Output
    where T::Ok: 'static
    {
        let mut ser_erased = erased_serde::Serializer::erase(ser);
        // pass the type-erased serializer to my type registry...
    }
```

erased_serde::Serializer::erase has this signature:

```rust
    pub fn erase<S>(serializer: S) -> erase::Serializer<S>
    where
        S: serde::Serializer,
        S::Ok: 'static,
    {
```

To call this function, S::Ok must be bound to 'static

Unfortunately, bincode::SerializerAcceptor's trait bounds are not compatible with this. I don't see a good way to both implement SerializerAcceptor and also pass the provided serializer to erased_serde::Serializer::erase

### Add the trait bound to bincode

This is a simple one-liner change, but I don't understand the implications of it enough to know if it's a good idea or not. It does however fix my particular use-case.

https://github.com/aclysma/bincode/commit/d97ed92660311a3c383824ebf69e5e060259ff16

### Make bincode serializers public

I imagine the keeping serializers out of the public API was a very intentional decision, so I can understand this probably wouldn't be accepted as a pull request. However, most other serde serializer/deserializer crates that I've seen expose these types, and I've consequently found them easier to work with. This one fixes my use-case and ends up being simpler because I don't have to bother with implementing SerializerAcceptors and DeserializerAcceptors

https://github.com/aclysma/bincode/commit/69a3917dee9270993cd2b4dba0d18a74ede27858

## Conclusion

Any advice here on what the best way forward would be? Would the first change be accepted as a PR, or is there a good reason not to add the trait bound? Thanks!

**Comment by jdm** [comment]
This sounds a bit similar to #300. Exposing DefaultOptions seems like an ok first step to me.

**Comment by aclysma** [comment]
I think I'd need to expose more than just DefaultOptions in order to create a serializer directly.. did I miss something?

**Comment by jdm** [comment]
I believe it would be possible to use `Serializer::new(DefaultOptions::new())` if DefaultOptions and its constructor were made public.

**Comment by aclysma** [comment]
Sorry for the delayed response! I may be misunderstanding... are you suggesting making `bincode::ser::Serializer` public? This requires a few more things being made public. I tried this in the change mentioned above and it worked for me (although it would be better to add docs rather than disable the no-docs warning): https://github.com/aclysma/bincode/commit/69a3917dee9270993cd2b4dba0d18a74ede27858 

Should I PR that or did I misunderstand the suggestion? Thanks!

**Comment by aclysma** [comment]
Just a quick update, tonight I noticed that just picking up PR #288 fixes this for me. Are there plans to publish a new version that includes this change?

**Comment by ZoeyR** [comment]
Closing this since we now expose the `Serializer` and `Deserializer` directly. There may still be some issues since I believe `erased_serde` uses `deserialize_any`, which bincode does not support, but these issues should be opened on the `erased_serde` repo.
