### ISSUE TITLE
[support] [feature] Configuration to omit the length of slices

### ISSUE THREAD

**Issue by niedzielski** [servo/bincode#316]
I'm a Rust newbie. I use bincode v1.2.1 to serialize `Vec<_>` to a `&[u8]` for passing to [WebGL](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.buffer_data_with_u8_array). Unfortunately, it doesn't seem to be possible to omit the slice's length header. E.g.:

```rust
extern crate bincode;

#[repr(C)]
#[derive(serde::Serialize)]
struct Foo {
  bar: u8
}

fn main() {
  // Ok.
  let foo = Foo { bar: 65 };
  let bytes = bincode::config().serialize(&foo).unwrap();
  assert_eq!(bytes, [65]);

  // Ok, fixed in https://github.com/servo/bincode/issues/86.
  let foos = [Foo { bar: 65 }, Foo { bar: 66 }];
  let bytes = bincode::config().serialize(&foos).unwrap();
  assert_eq!(bytes, [65, 66]);

  // The next test fails:
  //   thread 'main' panicked at 'assertion failed: `(left == right)`
  //    left: `[2, 0, 0, 0, 0, 0, 0, 0, 65, 66]`,
  //   right: `[65, 66]`', src/main.rs:26:3
  let foo_vec = vec![Foo { bar: 65 }, Foo { bar: 66 }];
  let bytes = bincode::config().serialize(&foo_vec[..]).unwrap();
  assert_eq!(bytes, [65, 66]);
}
```

WebGL just wants a pointer and a size. As a workaround, I end up doing something like this before passing the data:

```rust
for _ in 0..8 {
  bytes.remove(0);
}
```

[The example](https://github.com/servo/bincode/blob/e7aa623/examples/basic.rs#L21) and [tests](https://github.com/servo/bincode/blob/e7aa623/tests/test.rs#L15) seem to indicate that bincode is primarily for going to and from bincode itself, and maybe not so much C APIs(?).

If it makes sense, can a [configuration option](https://github.com/servo/bincode/blob/e7aa623/src/config.rs#L98) be provided to omit the sizing informational header for serialization of dynamic length slices (passing relationship to #86)?

Thank you so much for the great library! :+1:

**Comment by ZoeyR** [comment]
There's not really a way to remove the size header, since on deserialization bincode would need to know the size.

**Comment by ZoeyR** [comment]
From your example it seems like you would be better off using something like iterators and collect. serializers will induce a lot of unnecessary overhead.

**Comment by niedzielski** [comment]
@ZoeyR, thank you for such a quick clarification! I've updated my question which wasn't as clear as I had intended in case others stumble upon this case. Thanks again for the quick resolution! :+1:

**Comment by ZoeyR** [comment]
@niedzielski a better form of your workaround (instead of using bincode at all) would look something like this:

```rust
let foo_vec_vec = vec![vec![Foo { bar: 65 }], vec![Foo { bar: 66 }]];
let bytes = foo_vec_vec
    .iter()
    .flatten()
    .map(|foo| foo.bar)
    .collect::<Vec<_>>();
    
assert_eq!(bytes, [65, 66]);
```

**Comment by niedzielski** [comment]
@ZoeyR, thank you for the tip! I will have to study on it more but my actual use case is less simple. The bar field is complex so bincode is helpful in serializing it. I guess my example wasn't so good! It is actually closer to:

```rust
#[repr(C)]
#[derive(serde::Serialize)]
struct Foo {
  bar: Vec<Bar>
}

#[repr(C)]
#[derive(serde::Serialize)]
struct Bar {
  a: u8,
  b: f64,
  // Other fields.
}

fn main() {
  let foo = vec![Foo {bar: vec![Bar{a: 1, b: 2.}]}];
  let bars: Vec<Bar> = foo
    .iter()
    .map(|foo| foo.bar) // Requires a move.
    .flatten()
    .collect::<Vec<_>>();
    
  // ...
}
```

I wanted to avoid cloning the `Vec<Bar>` in the foo.bar field. I had thought it was a good opportunity to do the serialization there but that causes the issue where the serialized results cannot be concatenated without manually removing sizing information.

**Comment by ZoeyR** [comment]
Do you have the original code? I'm curious as to what exactly WebGL is wanting here. CC @strega-nil since she may have an idea on how to better solve your problem.

**Comment by niedzielski** [comment]
@ZoeyR, sorry, the original code is not in a state I can share at the moment :[ Please don't trouble yourself any more than you already have!

[WebGL does expect a slice](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebGlRenderingContext.html#method.buffer_data_with_u8_array) (I had originally reported it as expecting a pointer and a size incorrectly prior to [my first comment](#issuecomment-607046454)). The only reason I'm having an issue is because I am trying to coalesce vectors using bincode as an intermediate step. Maybe this example would be clearer:

```rust
struct QueryResult<T> {
  items: Vec<T>
}

struct RenderableString {
  x: f32,
  y: f32,
  text: Vec<Sprite>
}

#[repr(C)]
#[derive(serde::Serialize)]
struct Sprite {
  // WebGL attributes to be serialized
}

fn main() {
  let result: QueryResult<RenderableString> = QueryResult {items: RenderableString { x: 1., t: 2. text: vec![Sprite { ... }, Sprite { ... }, Sprite { ... } ] } };

  let sprites: Vec<Sprite> = result.items
    .iter()
    .map(|renderable_string| renderable_string.text)
    .flatten()
    .collect();
  let bytes = bincode::config().serialize(&sprites[..]).unwrap();

  // I can't do the above step because the mapping requires a move.
  // If instead I map to a serialized intermediate result, I get the header sizing
  // embedded for each RenderableString.text.
}
```
