### ISSUE TITLE
Could a new version be published?

### ISSUE THREAD

**Issue by aclysma** [servo/bincode#321]
I had originally opened this issue: https://github.com/servo/bincode/issues/301

It was resolved for me with the changes on Jan 23, 2020 like this one:
https://github.com/servo/bincode/commit/e30e91e3a7d24925f09fdbd96773245a72fd7537

However, I'm still having to depend on the git repo rather than a published crate. Would it be possible to publish a version of this crate that includes this change?

**Comment by ZoeyR** [comment]
There's still some more changes that I want to get finished before I publish a new version. I also need to refresh the documentation.

**Comment by jonhoo** [comment]
It'd be great to also get #310 out there :D

**Comment by aclysma** [comment]
Just last night I updated to the most recent version of bincode. I think we can all agree that the new API is a big improvement. 😄   https://github.com/kabergstrom/prefab/pull/3/commits/67aad217b5b0e1249f5b0f682c509cf8aefc4831

**Comment by ZoeyR** [comment]
I'm finishing up the announcement blog post right now! Should be out today or tomorrow

**Comment by ZoeyR** [comment]
Aaaaand published!

**Comment by jonhoo** [comment]
@ZoeyR Could you share a link to the blog post?

**Comment by ZoeyR** [comment]
@jonhoo https://dos.cafe/blog/bincode-1.3.html

**Comment by aclysma** [comment]
Thanks for the amazing work on this!
