### ISSUE TITLE
Binary file problems

### ISSUE THREAD

**Issue by rkfox** [servo/bincode#322]
I'm trying to write serialized documents to file, but I'm getting a lot of errors when I try to deserialize these objects from the disk; around 10% of saved documents are discarded by bincode. I tested using one document repeatedly and it appears that they are read with varying lengths. I don't think the problem is with BufWriter or BufReader which I use to read/write. The length of the serialized data is consistent before written to the disk. I seem to be having issues separating the documents when reading from the disk as my read strategy returns varying lengths of documents. I'm not sure if this is related to bincode or not, but I don't have any issues when I use other serialization methods.

**Comment by ZoeyR** [comment]
Can you provide a reproducible sample? This doesn't immediately sound related to bincode but I'll look into it to make sure.

**Comment by rkfox** [comment]
I'm not sure what the problem is. I thought it might be that bincode doesn't support nested structs, but that isn't the case; I tried writing a simplified example to replicate the problem, but I can't reproduce the issue.

**Comment by ZoeyR** [comment]
Thanks! Yeah, I'll close the issue for now. If you ever do get a repro, feel free to file another issue.
