### ISSUE TITLE
Configurable enum encoding/decoding

### ISSUE THREAD

**Issue by michaeleberhardt310** [servo/bincode#327]
Hi there,

would it be possible to configure the type an enum will be encoded/decoded, e.g. forcing a certain enum to be encoded into an u8 instead of u32? This point is interesting to me for the reason of high performance applications, in which it matters if you have to transfer 4 bytes of data or only 1...

u32/usize encoding as a default for enums seems to me a very good solution in regular applications, where performance doesn't matter, but for a few enum definitions in my code, such an opportunity would be awesome.

Kind regards,
Michael

**Comment by ZoeyR** [comment]
@michaeleberhardt310 we recently merged a varint configuration mode that will automatically compress numbers in PR #306. This will be published in the next release of bincode.
