### ISSUE TITLE
Expose Serializer 

### ISSUE THREAD

**Issue by RunDevelopment** [servo/bincode#331]
I have a single `std::io::Write` and want to serialize multiple values into a file (appending them one after another (I keep track of where everything is myself)). 

Right now, there is no way to do that because the `bincode::ser::Serializer` isn't public.

Any other way to make this possible is also acceptable of curse.

**Comment by RunDevelopment** [comment]
On second thought, I'll just make a cheap wrapper around a `Vec` and go about my day.

Sorry for taking up your time.

**Comment by ZoeyR** [comment]
Our master branch does expose `Serializer` now. I just haven't published the changed to crates.io
