### ISSUE TITLE
Regression in 1.3.0: memory allocation of 8391155392347897856 bytes failed

### ISSUE THREAD

**Issue by dtolnay** [servo/bincode#335]
Can be reproduced by adding the following test to the bottom of src/lib.rs in https://github.com/sharkdp/bat/tree/b09d245dea7e2f45cf461fda978f3256e7162465 and running `cargo update` and `cargo test --lib bincode_repro`. It succeeds with bincode 1.2.1 and aborts with 1.3.0.

 ```rust
#[test]
fn bincode_repro() {
     use syntect::{dumps::from_binary, parsing::SyntaxSet};
     from_binary::<SyntaxSet>(include_bytes!("../assets/syntaxes.bin"));
}
```

```console
memory allocation of 8391155392347897856 bytes failederror: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/git/tmp/bat/target/debug/deps/bat-3446bc567e169f19 repro` (signal: 6, SIGABRT: process abort signal)
```

I've yanked 1.3.0 for now since it's important to keep old serialized data deserializing across minor versions.

**Comment by ehuss** [comment]
The regression seems to start with https://github.com/servo/bincode/pull/309.  I'm uncertain, but it seems like [`fill_buffer`](https://github.com/servo/bincode/blob/f5fa06e761646ba083c1317a4ba0dcd58eefe99b/src/de/read.rs#L143-L154) was written to assume that it will only add at most `length` bytes to the buffer. However, the new implementation allows reading more than `length` if the size of the temp_buffer is already larger than `length`.

**Comment by ZoeyR** [comment]
@dtolnay I'm not sure why this needed a version yank. Especially when the only replacement version has undefined behavior. It looks to me like this is an edge case regression, which normally wouldn't require a yank.

I also can't even repro this issue locally.

**Comment by dtolnay** [comment]
Regarding the yank -- it's because taking correct code that used to work (bat, cargo-expand, etc) and making them not work is extremely disruptive. That disruption is not offset by making things work that didn't used to work, or even removing UB. The latter things can be re-released in a way where no disruption needs to occur. Yanks are intended for this.

> It looks to me like this is an edge case regression

I'm not sure how much you got a chance to investigate the regression but this sounds premature to me. I don't know how to tell that without understanding the bug better. In particular I don't know whether *all* or *most* past serialized bincode data might be broken.

**Comment by ZoeyR** [comment]
It doesn't repro at all on my machines. On other's machines where it does repro the "fix" ends up causing a panic inside of syntect. (The fix being replacing line 151 with `self.reader.read_exact(&mut self.temp_buffer[..length])?;`). Since the reader in this case comes from ffi of the `flate2` crate. Are we sure there isn't some UB causing this?

**Comment by stevenliebregt** [comment]
I still get an error like this on bincode `1.3.3`, serializing goes fine, but when I deserialize the same file it gives this error
