### ISSUE TITLE
custom IntEncoding?

### ISSUE THREAD

**Issue by timbod7** [servo/bincode#340]
It seems that the `IntEncoding` trait  is not exposed from the `bincode::config` module. Is this intentional or an oversight?

It would be useful to provide a custom `IntEncoding` impl for interoperability with other code.

**Comment by ZoeyR** [comment]
None of the config traits are exposed and implementable. This is intentional since those Traits may change at any time. I'm curious what interoperability you're trying to accomplish, `bincode` is its own encoding format so there really won't be any compatibility with others.

**Comment by timbod7** [comment]
I'm interoperating with some existing dart code.bincode would work as required, except that I need 32 bits for sizes.

I guess I'll create a fork.

**Comment by ZoeyR** [comment]
Is dart 32bit only?

**Comment by ZoeyR** [comment]
I'm also confused as to what you mean by interoperating with dart code. Are you calling into Rust from dart or did you write a bincode impl in dart?

**Comment by timbod7** [comment]
I have an existing system with dart <-> C++ interoperability with straightforward binary serialization. I want to start using rust in this environment.

It turns out that bincode is compatible with this existing serialization, except for the fact that vector sizes need to  be 32 bit.

**Comment by ZoeyR** [comment]
So it sounds like you're trying to mix two different binary serializers?

**Comment by timbod7** [comment]
Via [ADL](https://github.com/timbod7/adl) I have consistent data types in three languages: dart, c++ and rust.

 I have 2 binary serializers already - one for c++ and one for dart. I need a compatible one for rust.  bincode almost does the job.

**Comment by timbod7** [comment]
This fork is meeting my needs:

https://github.com/helix-collective/bincode
