### ISSUE TITLE
Get length of deserialized object

### ISSUE THREAD

**Issue by BlackYoup** [servo/bincode#343]
Hello,

I'm currently using bincode to serialize and deserialize structs over the network. Those structs can have a lot of data (up to 1MB for now but it can be more I guess). I read a network stream and decode messages from there. But sometimes the network stream might have multiple messages waiting to be deserialized. But because I don't know the deserialized struct length, I can't advance my network buffer to parse the next message, if any.

The only way I found for now is to use the `serialized_size` function to get the length but it feels a bit too much to serialize again the (possibly big) structure to advance my buffer with the size.

Would it be possible / make sense to access such length when I call `deserialize`? Or am I missing something here?

What I'm currently doing:

```rust
let src: BytesMut = ..;
match bincode::deserialize(&src) {
      Ok(decoded) => {
        let sz = bincode::serialized_size(&decoded)?;
        src.advance(sz as _);

        Ok(Some(decoded))
      },
      Err(e) => panic!()
}
```

Thanks

**Comment by ZoeyR** [comment]
If `BytesMut` implements `Read` you could use `bincode::deserialize_from`

**Comment by BlackYoup** [comment]
Yes you're right, I thought about it at some point but BytesMut or Bytes (from the bytes crate) doesn't implement Read. I shall explore this idea a bit more though.

**Comment by ZoeyR** [comment]
if you're using `BytesMut` from the `bytes` crate then their should be a `reader()` method to create a reader.

**Comment by BlackYoup** [comment]
Thanks for your help here :)

Yes there is but it doesn't quite solve my issue. When deserializing my stream, I check for the `io::error::UnexpectedEof` error to know that a message is not yet entirely received and if so, I'll try to parse my buffer later. Unfortunately, the `deserialize_from` method will  `advance()` the `BytesMut` regardless of if it successfully deserialized the bytes or not. I tried to implement my own `io::Read` trait to consume the internal `BytesMut` only once the deserialization is successful but since the reader is consumed by the `deserialized_from` function, I don't own it anymore and I can't really access it.

For a bit more context, I'm implementing this Trait to decode my data https://docs.rs/futures_codec/0.4.1/futures_codec/trait.Decoder.html to pass it to something that will read my socket https://docs.rs/futures_codec/0.4.1/futures_codec/struct.Framed.html

I'm pretty sure I'm just fighting the tools instead of using something else that would better fit my needs.

**Comment by BlackYoup** [comment]
Hello,

So I didn't know that I could pass a mutable reference of a reader to `deserialize_from()` so that's what I ended up doing. I also implemented a custom `io::Reader` trait to only consume the internal buffer once the message has been successfully parsed.

I'll let this issue open as a feature request but feel free to close it if you feel this isn't appropriate. I can also try to implement such feature if you agree with it.

**Comment by ZoeyR** [comment]
`Read` is also implemented for byte slices directly. The `deserialize` method was meant for cases where you know exactly how much data makes up your serialized objects, for all other cases where you don't know it is recommended to use `deserialize_from` instead.

**Comment by ZoeyR** [comment]
@BlackYoup I had a question come up for you. How do you know that the slice you were passing to `deserialize` had all the data for what you wanted to deserialize?

The reason I'm asking is that if you know it has enough, why don't you know how much is enough?

**Comment by BlackYoup** [comment]
@ZoeyR I didn't know that I had all the data. I know I have some data available and how much is available, I don't know if it's the whole structure or a part of it or the whole structure and part of another one etc..
