### ISSUE TITLE
Is it safe to use for locale storage - even storing very big structs?

### ISSUE THREAD

**Issue by mezeipetister** [servo/bincode#349]
Hi Guys,

we are looking for a binary serialization solution to our in-house in-memory db. It mainly storing objects in memory,
and save it to the disk when data update occurs. We have tested bincode and it's awesome, but is it mature enough
to use very safely for data serialization as a storage? So is there any chance, that a long running process, serializing data structs and save them to the local disk; after a year of running, after a restart, somehow would not be able to deserialize the objects?

Till now we used yaml serialization, but bincode is way more performant.

I did read that between minor version updates, bincode is safe. But I could not find an RFC standard for bincode. So as it seems to be not a standard, is there any way for breaking changes in serialization format?

Thank you in advance!

**Comment by mezeipetister** [comment]
Never mind, I trust you guys.

**Comment by ZoeyR** [comment]
There is no RFC standard. I am currently working on writing a standard but it may never become an IETF standard since those are notoriously difficult to get. Right now we guarantee that minor version changes will not break existing code.
