### ISSUE TITLE
Bincode fails to deserialize data that was just serialized with it

### ISSUE THREAD

**Issue by wingertge** [servo/bincode#350]
If I encode my serializable data and then immediately deserialize it, the decoding fails with `invalid value: integer "1", expected variant index 0 <= i < 1`. The same data serializes and deserializes perfectly with other `serde` libraries like RON.

This is the data model that fails to properly serialize/deserialize with the irrelevant stuff stripped out: 

[https://pastebin.com/Cdg0TavJ](https://pastebin.com/Cdg0TavJ)

My first guess would be the serde shim but it's hard to debug bincode errors

**Comment by ZoeyR** [comment]
Can you provide the code that serializes and deserializes?

**Comment by ZoeyR** [comment]
This could be a manifestation of https://github.com/servo/bincode/issues/184. Long story short `serde_derive` is broken.

**Comment by wingertge** [comment]
Actually I just looked in detail at every serde attribute and there's an `untagged` enum deep in the hierarchy on a type built into `amethyst` which I can't change. I understand bincode can't support that for technical reasons. Guess I'll need to use fast compression or something to keep my file sizes down without using bincode.

**Comment by ZoeyR** [comment]
Yeah, unfortunately you ran into one of the many things bincode cannot support. While serde is a general purpose serialization framework many of its more advanced features were only designed to work with self-describing formats, where the shape of the data is encoded with the data. Bincode is not self-describing and so it can't support many of these things.
