### ISSUE TITLE
Serialized size difference between b".." and "..".as_bytes()

### ISSUE THREAD

**Issue by mezeipetister** [servo/bincode#351]
Hi Guys,

why is there a size difference when I do the following?

```rust
let size = bincode::serialized_size(b"hellobello").unwrap();
// here the size is 10

let size = bincode::serialized_size("hellobello".as_bytes()).unwrap();
// here the size is 18
```

So with the following bytes - as valid ASCII characters - should take 1 byte per character, that means 10 char * 1 byte => 10 bytes.
But when I use a &[u8] or a "..".as_bytes(), the size is almost double. Why?

Thank you in advance.

**Comment by mezeipetister** [comment]
Solved here: https://users.rust-lang.org/t/bincode-serialized-size-difference-between-b-and-as-bytes/48541/2

**Comment by ZoeyR** [comment]
If you use the bincode varint configuration you can end up reducing the side of the `as_bytes()` case to 11 bytes in size.
