### ISSUE TITLE
Treat as iter?

### ISSUE THREAD

**Issue by jguhlin** [servo/bincode#352]
Is it possible to treat a stream of bincode's as an iter without the cost of deserializing? I'm using it for some ML and would like to randomize the bincode'd structs, so can iterate through finding the byte offset of each, but at the cost of deserializing everything along the way.

I know it's not quite the original intent of bincode, but it's worked remarkably well for me so far. Cheers

**Comment by ZoeyR** [comment]
You would need to wrap the serialized bincode items with your own delimiter. Since bincode is not self-describing there is no way to know where one item ends without deserializing.

**Comment by jguhlin** [comment]
Ah, makes sense. Was hoping one was already there. Thanks though! I'll try to index it when I do the initial compression, I think that's the best option. Cheers.
