### ISSUE TITLE
Why serialize_len uses u64 and not u32

### ISSUE THREAD

**Issue by nearmax** [servo/bincode#353]
It seems unnecessary to encode the length of a sequence using `u64` and not `u32`, since it is unlikely that some practical collection has more than `2^32-1` elements. Except maybe collections of zero size objects which are a special case anyway.

**Comment by ZoeyR** [comment]
Collections of zero sized objects do end up going through the same codepath, so serializing as a u64 is more portable. If you wish to conserve space consider turning on the varint option.
