### ISSUE TITLE
[Q] How to serialize/deserialize vector whose length is u32 (not u64)?

### ISSUE THREAD

**Issue by InspectorDue** [servo/bincode#357]
I have data where 4 initial bytes (u32) is length of vector. But I can't deserialize data (like in example) because length of the vector is 4 bytes (u32 not u64).
I can read first 4 bytes and then in loop read data and write it to vector. (What about performance?) 
Or I can insert 4 bytes to the beginning of the vector.

**Comment by ZoeyR** [comment]
Was this data serialized with bincode?

**Comment by InspectorDue** [comment]
No.

**Comment by ZoeyR** [comment]
Bincode is not designed to deserialize data created with other serialization formats. You will need to write the deserialization code yourself.
