### ISSUE TITLE
How to set big_endian in options?

### ISSUE THREAD

**Issue by PerMagnusH** [servo/bincode#362]
Hi, I'm rather new to Rust, and have big troubles using DefaultOptions to set endianness.
It says that the use of config() is deprecated and that I should use settings() instead, but I can't find how to set endianness with that new way.

I tried the following:

settings.with_big_endian()

but then it complains there is no with_big_endian function.

Please help me to understand how I can set big-endian mode.

For now, I will use the old way of doing this with config(), that is:

use bincode::config; 
config().big_endian().serialize_into(&mut file, &world).unwrap();

But I really would like to use the "new" way if possible.

**Comment by ZoeyR** [comment]
`options().with_big_endian()` works, but you also need to import `bincode::Options`

**Comment by PerMagnusH** [comment]
Ah yes! After I did import of bincode::Options it worked!
Thank you very much for fast answer! Issue closed.
