### ISSUE TITLE
Issue deserializing with nested types

### ISSUE THREAD

**Issue by Nashtare** [servo/bincode#371]
I am having a serialization error with bincode that I couldn't solve with a satisfying solution.

I have main struct `MainStruct` where the last field is of type 
`HashMap<MyStruct1, Vec<MyStruct2>>`
where `Mystruct1`, `MyStruct2` are custom structs not containing any collections inside. They both have a working implementation of `Serialize` and `Deserialize`. 

The error message I get is
`Bincode(Custom("invalid length 1, expected struct MyStruct2"))`, it always reads the sequence as 1 element while the struct contains 5 fields (each with primitive types).

I noticed however that deserialization of the `MainStruct` always fails when deriving `Serialize` and `Deserialize` traits. I tried flattening but got an error that is already mentioned here. A working solution is to first serialize the `Vec<MyStruct2>`, then serialize a second time on top of it but this is pretty ugly. 

I am not so used to Serde serialization, so maybe there is a known workaround that I am not aware of.. Would you have any input?

**Comment by ZoeyR** [comment]
Can you produce a minimal reproduction so that I can look into this?

**Comment by Nashtare** [comment]
Hmm it seems there was an issue on my side, I'll close the issue then. Sorry for the inconvenience!
